// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMFMW51W6qvW9_uzge7zWgp5pwPwtWqM8',
    appId: '1:267368087367:web:e8cd8aac5c1bab00b05662',
    messagingSenderId: '267368087367',
    projectId: 'auction-4bb68',
    authDomain: 'auction-4bb68.firebaseapp.com',
    storageBucket: 'auction-4bb68.appspot.com',
    measurementId: 'G-ET0EHQT7TP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkOKylWdd6Yol4P4tsJP6mrYVVSyiPAKs',
    appId: '1:267368087367:android:3c685c8314bd80ddb05662',
    messagingSenderId: '267368087367',
    projectId: 'auction-4bb68',
    storageBucket: 'auction-4bb68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwGFoMVQG1D3QQ28YjeAnSM7o8LmQodns',
    appId: '1:267368087367:ios:f7fb3e214b78bd7fb05662',
    messagingSenderId: '267368087367',
    projectId: 'auction-4bb68',
    storageBucket: 'auction-4bb68.appspot.com',
    iosBundleId: 'com.example.auctionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwGFoMVQG1D3QQ28YjeAnSM7o8LmQodns',
    appId: '1:267368087367:ios:f4c16c1a7cc6c5bdb05662',
    messagingSenderId: '267368087367',
    projectId: 'auction-4bb68',
    storageBucket: 'auction-4bb68.appspot.com',
    iosBundleId: 'com.example.auctionApp.RunnerTests',
  );
}
